import type { HskEntry, VocabularyWord, Radical } from "@/types";
import { toPinyin, toPinyinPlain } from "./pinyin";

// ─── Static dataset ───────────────────────────────────────────────────────────
// Generated by: pnpm build:dataset  (scripts/build-dataset.mjs)
// Contains all HSK 1-7 words with pre-translated Vietnamese meanings.
import rawData from "@/data/hsk-processed.json";

const wordPool: HskEntry[] = rawData as HskEntry[];

export function fetchWordPool(): HskEntry[] {
  return wordPool;
}

// ─── Radical decomposition ────────────────────────────────────────────────────
const RADICAL_MAP: Record<string, { meaning: string; pinyin: string }> = {
  一: { meaning: "one", pinyin: "yī" },
  丨: { meaning: "line", pinyin: "gǔn" },
  丶: { meaning: "dot", pinyin: "zhǔ" },
  丿: { meaning: "slash", pinyin: "piě" },
  乙: { meaning: "second", pinyin: "yǐ" },
  二: { meaning: "two", pinyin: "èr" },
  亠: { meaning: "lid", pinyin: "tóu" },
  人: { meaning: "person", pinyin: "rén" },
  儿: { meaning: "legs", pinyin: "ér" },
  入: { meaning: "enter", pinyin: "rù" },
  八: { meaning: "eight", pinyin: "bā" },
  冫: { meaning: "ice", pinyin: "bīng" },
  刀: { meaning: "knife", pinyin: "dāo" },
  力: { meaning: "power", pinyin: "lì" },
  十: { meaning: "ten", pinyin: "shí" },
  厂: { meaning: "cliff", pinyin: "hǎn" },
  又: { meaning: "again", pinyin: "yòu" },
  口: { meaning: "mouth", pinyin: "kǒu" },
  囗: { meaning: "enclosure", pinyin: "wéi" },
  土: { meaning: "earth", pinyin: "tǔ" },
  士: { meaning: "scholar", pinyin: "shì" },
  夕: { meaning: "evening", pinyin: "xī" },
  大: { meaning: "big", pinyin: "dà" },
  女: { meaning: "woman", pinyin: "nǚ" },
  子: { meaning: "child", pinyin: "zǐ" },
  宀: { meaning: "roof", pinyin: "mián" },
  寸: { meaning: "inch", pinyin: "cùn" },
  小: { meaning: "small", pinyin: "xiǎo" },
  尸: { meaning: "corpse", pinyin: "shī" },
  山: { meaning: "mountain", pinyin: "shān" },
  工: { meaning: "work", pinyin: "gōng" },
  己: { meaning: "self", pinyin: "jǐ" },
  巾: { meaning: "cloth", pinyin: "jīn" },
  干: { meaning: "dry", pinyin: "gān" },
  广: { meaning: "shelter", pinyin: "guǎng" },
  弓: { meaning: "bow", pinyin: "gōng" },
  彡: { meaning: "hair", pinyin: "shān" },
  彳: { meaning: "step", pinyin: "chì" },
  心: { meaning: "heart", pinyin: "xīn" },
  戈: { meaning: "spear", pinyin: "gē" },
  户: { meaning: "door", pinyin: "hù" },
  手: { meaning: "hand", pinyin: "shǒu" },
  文: { meaning: "script", pinyin: "wén" },
  斤: { meaning: "axe", pinyin: "jīn" },
  方: { meaning: "square", pinyin: "fāng" },
  日: { meaning: "sun/day", pinyin: "rì" },
  月: { meaning: "moon/month", pinyin: "yuè" },
  木: { meaning: "tree/wood", pinyin: "mù" },
  止: { meaning: "stop", pinyin: "zhǐ" },
  毛: { meaning: "fur", pinyin: "máo" },
  气: { meaning: "steam/air", pinyin: "qì" },
  水: { meaning: "water", pinyin: "shuǐ" },
  火: { meaning: "fire", pinyin: "huǒ" },
  父: { meaning: "father", pinyin: "fù" },
  牛: { meaning: "cow", pinyin: "niú" },
  犬: { meaning: "dog", pinyin: "quǎn" },
  玉: { meaning: "jade", pinyin: "yù" },
  生: { meaning: "life/birth", pinyin: "shēng" },
  用: { meaning: "use", pinyin: "yòng" },
  田: { meaning: "field", pinyin: "tián" },
  白: { meaning: "white", pinyin: "bái" },
  皮: { meaning: "skin", pinyin: "pí" },
  目: { meaning: "eye", pinyin: "mù" },
  石: { meaning: "stone", pinyin: "shí" },
  禾: { meaning: "grain", pinyin: "hé" },
  穴: { meaning: "cave", pinyin: "xué" },
  立: { meaning: "stand", pinyin: "lì" },
  竹: { meaning: "bamboo", pinyin: "zhú" },
  米: { meaning: "rice", pinyin: "mǐ" },
  羊: { meaning: "sheep", pinyin: "yáng" },
  羽: { meaning: "feather", pinyin: "yǔ" },
  老: { meaning: "old", pinyin: "lǎo" },
  耳: { meaning: "ear", pinyin: "ěr" },
  肉: { meaning: "flesh", pinyin: "ròu" },
  自: { meaning: "self", pinyin: "zì" },
  舌: { meaning: "tongue", pinyin: "shé" },
  舟: { meaning: "boat", pinyin: "zhōu" },
  色: { meaning: "color", pinyin: "sè" },
  虫: { meaning: "insect", pinyin: "chóng" },
  血: { meaning: "blood", pinyin: "xuè" },
  行: { meaning: "walk/travel", pinyin: "xíng" },
  衣: { meaning: "clothes", pinyin: "yī" },
  见: { meaning: "see", pinyin: "jiàn" },
  角: { meaning: "horn/angle", pinyin: "jiǎo" },
  言: { meaning: "speech", pinyin: "yán" },
  谷: { meaning: "valley", pinyin: "gǔ" },
  豆: { meaning: "bean", pinyin: "dòu" },
  贝: { meaning: "shell/money", pinyin: "bèi" },
  走: { meaning: "walk/run", pinyin: "zǒu" },
  足: { meaning: "foot", pinyin: "zú" },
  身: { meaning: "body", pinyin: "shēn" },
  车: { meaning: "vehicle", pinyin: "chē" },
  金: { meaning: "metal/gold", pinyin: "jīn" },
  门: { meaning: "gate/door", pinyin: "mén" },
  隹: { meaning: "bird", pinyin: "zhuī" },
  雨: { meaning: "rain", pinyin: "yǔ" },
  青: { meaning: "blue-green", pinyin: "qīng" },
  食: { meaning: "eat/food", pinyin: "shí" },
  首: { meaning: "head", pinyin: "shǒu" },
  香: { meaning: "fragrant", pinyin: "xiāng" },
};

export function getRadicals(hanzi: string): Radical[] {
  const chars = [...hanzi];
  const results: Radical[] = [];
  const seen = new Set<string>();
  for (const char of chars) {
    if (seen.has(char)) continue;
    seen.add(char);
    const info = RADICAL_MAP[char];
    if (info) results.push({ char, meaning: info.meaning, pinyin: info.pinyin });
  }
  return results;
}

// ─── Build a full VocabularyWord from a static HskEntry ───────────────────────
export function buildVocabWord(entry: HskEntry, id: string): VocabularyWord {
  const pinyinResolved = entry.pinyin || toPinyin(entry.hanzi);
  const pinyinPlain = toPinyinPlain(entry.hanzi);
  const radicals = getRadicals(entry.hanzi);

  return {
    id,
    hanzi: entry.hanzi,
    pinyin: pinyinResolved,
    pinyinPlain,
    vietnamese: entry.vietnamese,
    english: entry.english,
    radicals,
    hskLevel: entry.hsk,
  };
}
