export interface Radical {
  char: string;
  meaning: string;
  pinyin: string;
}

export interface VocabularyWord {
  id: string;
  hanzi: string;
  pinyin: string; // with tone marks e.g. "xuéxí"
  pinyinPlain: string; // no tones e.g. "xuexi"
  vietnamese: string;
  english: string;
  radicals: Radical[];
  hskLevel: number;
}

export type TestStatus = "idle" | "running" | "finished";

export interface TestQuestion {
  word: VocabularyWord;
  userAnswer: string;
  isCorrect: boolean | null;
}

// Processed entry — shape of every object in src/data/hsk-processed.json
// Generated by: node scripts/build-dataset.mjs
export interface HskEntry {
  id: string;
  hanzi: string;
  pinyin: string;
  english: string;
  vietnamese: string;
  hsk: number;
}

